In [1]:
import nltk
from nltk.corpus import stopwords

In [2]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Jonas\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [3]:
stopwords_en = set(stopwords.words('english'))

In [4]:
print(f"Total de stopwords em inglês: {len(stopwords_en)}")

print(f"Lista das 10 primeiras stopwords: {list(stopwords_en)[:10]}")

Total de stopwords em inglês: 179
Lista das 10 primeiras stopwords: ["it's", 'mustn', 'are', "mightn't", 'is', 'yourselves', 'such', "doesn't", 'they', 'other']

In [5]:
import pandas as pd

In [6]:
df = pd.read_csv('resources\dblp-v10-clean.csv')

In [7]:
pd.set_option('display.max_colwidth', None)
df[['id', 'abstract']].head()

,id,abstract
0,4ab3735c-80f1-472d-b953-fa0557fed28b,"In this paper, a robust 3D triangular mesh watermarking algorithm based on 3D segmentation is proposed. In this algorithm three classes of watermarking are combined. First, we segment the original image to many different regions. Then we mark every type of region with the corresponding algorithm based on their curvature value. The experiments show that our watermarking is robust against numerous attacks including RST transformations, smoothing, additive random noise, cropping, simplification and remeshing."
1,4ab39729-af77-46f7-a662-16984fb9c1db,"We studied an autoassociative neural network with dynamic synapses which include a facilitating mechanism. We have developed a general mean-field framework to study the relevance of the different parameters defining the dynamics of the synapses and their influence on the collective properties of the network. Depending on these parameters, the network shows different types of behaviour including a retrieval phase, an oscillatory regime, and a non-retrieval phase. In the oscillatory phase, the network activity continously jumps between the stored patterns. Compared with other activity-dependent mechanisms such as synaptic depression, synaptic facilitation enhances the network ability to switch among the stored patterns and, therefore, its adaptation to external stimuli. A detailed analysis of our system reflects an efficient-more rapid and with lesser errors-network access to the stored information with stronger facilitation. We also present a set of Monte Carlo simulations confirming our analytical results."
2,4ab3a4cf-1d96-4ce5-ab6f-b3e19fc260de,"It is well-known that Sturmian sequences are the non ultimately periodic sequences that are balanced over a 2-letter alphabet. They are also characterized by their complexity: they have exactly $(n+1)$ distinct factors of length $n$. A natural generalization of Sturmian sequences is the set of infinite episturmian sequences. These sequences are not necessarily balanced over a $k$-letter alphabet, nor are they necessarily aperiodic. In this paper, we characterize balanced episturmian sequences, periodic or not, and prove Fraenkel's conjecture for the special case of episturmian sequences. It appears that balanced episturmian sequences are all ultimately periodic and they can be classified in 3 families."
3,4ab3a98c-3620-47ec-b578-884ecf4a6206,"One of the fundamental challenges of recognizing actions is accounting for the variability that arises when arbitrary cameras capture humans performing actions. In this paper, we explicitly identify three important sources of variability: (1) viewpoint, (2) execution rate, and (3) anthropometry of actors, and propose a model of human actions that allows us to investigate all three. Our hypothesis is that the variability associated with the execution of an action can be closely approximated by a linear combination of action bases in joint spatio-temporal space. We demonstrate that such a model bounds the rank of a matrix of image measurements and that this bound can be used to achieve recognition of actions based only on imaged data. A test employing principal angles between subspaces that is robust to statistical fluctuations in measurement data is presented to find the membership of an instance of an action. The algorithm is applied to recognize several actions, and promising results have been obtained."
4,4ab3b585-82b4-4207-91dd-b6bce7e27c4e,"This paper generalizes previous optimal upper bounds on the minimum Euclidean distance for phase shift keying (PSK) block codes, that are explicit in three parameters: alphabet size, block length a ..."

In [8]:
df[['id', 'abstract']].tail()

,id,abstract
827528,feb7d7ee-58d8-4a48-853e-c6751957997e,"Abstract The article presents a narrative review of scholarship on social support through social networking sites (SNSs) published from 2004 to 2015. By searching keywords related to social support and SNSs in major databases for social sciences, we identified and content analyzed directly relevant articles (N = 88). The article summarizes the prevalence of theory usage; the function of theory usage (e.g., testing a theory, developing a theory); major theories referenced; and methodologies, including research designs, measurement, and the roles of social support and SNS examined in this literature. It also reports four themes identified across the studies, indicating the trends in the current research. Based on the review, the article presents a discussion about study sites, conceptualization of social support, theoretical coherence, the role of social networks, and the dynamic relationships between SNS use and social support, which points out potential avenues for shaping a future research agenda."
827529,ff21f451-e914-4948-b1e4-0ef5971b365c,"In MANETs, exchange of data is carried out with the help neighbouring nodes, and the destination node is identified with the broadcasting schemes. Broadcasting schemes are considered to increase the efficiency, and MPR broadcasting scheme is considered because of its reduced overhead. The message is broadcasted only to the selected MPR nodes, thus reducing flooding in the network. Nodes that are selected to act as the MPR nodes can be any neighbouring nodes, and there are no significant conditions that prove the MPR node's integrity. In this paper, we have proposed a novel approach in selecting the MPR nodes by adding an additional security feature before MPR node selection. Our security feature does not add any additional communicational overhead or data exchanges. We were also able to reduce the localisation error by using Mahalanobis distance and maximum-likelihood. Localisation techniques were used during simulation to verify the time constraints and efficiency."
827530,ff4623da-cc5a-4048-99ae-e5e906eb0a1b,"This paper presents a micro-power photovoltaic (PV) harvesting system. A H-bridge configuration DC-DC converter is designed to harvest PV energy and deliver energy to applications of Internet of Thing (IOT). The main converter consists of a single inductor with two inputs and two outputs. It regulates a constant 1V output voltage for several applications such as sensors and signal transmitters. The surplus energy is stored in a rechargeable battery. The battery also serves as a secondary input source to provide energy to the output load in heavy-load condition. Due to the limited energy of the system, the power consumption of the power system is optimized by several techniques. A perturb-and-observe maximum power point tracker (MPPT) is implemented to maximize the power extracted from the PV harvester. Pulse-width modulation (PWM) and pulse-frequency modulation (PFM) are used to regulate the output voltage. The controller is designed mainly in digital and free of power-hungry circuits. The proposed converter occupies an area of 1.44mm 2 . The estimated peak power efficiency is 84% while driving 3–10µA load current."
827531,ff6217c8-a649-4db3-95ec-e1c55195ef4e,"In this work, a distillation system is designed to purify dimethyl ether (DME) from its reaction by-products in the conversion of flare gas into a useful energy product. The distillation equipment has a size constraint for easy transportation, making process intensification the best strategy to efficiently separate the mixture. The process intensification distillation techniques explored include the dividing wall column (DWC) and a novel semicontinuous dividing wall column (S-DWC). The DWC and the S-DWC both purify DME to fuel grade purity along with producing high purity waste streams. An economic comparison is made between the two systems. The DWC is a cheaper method of producing DME however the purity of methanol, a reaction intermediate, is not as high as the S-DWC. Overall, this research shows that it is possible to purify DME and its reaction by-products in a 40-foot distillation column at a cost that is competitive with Diesel."
827532,ff87696d-35fb-4872-aab5-5ff6285f10e6,"The uninorms with continuous underlying t-norm and t-conorm are characterized via the ordinal sum construction of Clifford. Using the previous results of the author, where each uninorm with continuous underlying operations was characterized by properties of its set of discontinuity points, it is shown that each such a uninorm can be decomposed into an ordinal sum of a countable number of semigroups related to representable uninorms, continuous Archimedean t-norms, continuous Archimedean t-conorms and internal uninorms (including the min and the max operator)."

Realizando tokenização e removendo stopwords na coluna abstract

In [9]:
#remover stopwords
def remove_stopwords(text):
    # Verifica se o texto é uma string
    if isinstance(text, str):
        palavras = text.split()
        palavras_filtradas = [palavra for palavra in palavras if palavra.lower() not in stopwords_en]
        return ' '.join(palavras_filtradas)
    # Retorna o valor original se não for uma string (por exemplo, float)
    return text

In [10]:
#Removendo pontos, vírgulas e outros caracteres especiais mantendo o hífen de palavras compostas
df['abstract'] = df['abstract'].str.replace(r'[^\w\s-]', '', regex=True)

In [11]:
df['abstract'] = df['abstract'].apply(remove_stopwords)

In [12]:
df['abstract'] = df['abstract'].str.lower()

In [13]:
df['abstract'] = df['abstract'].str.split()

In [14]:
df[['id', 'abstract']].head()

,id,abstract
0,4ab3735c-80f1-472d-b953-fa0557fed28b,"[paper, robust, 3d, triangular, mesh, watermarking, algorithm, based, 3d, segmentation, proposed, algorithm, three, classes, watermarking, combined, first, segment, original, image, many, different, regions, mark, every, type, region, corresponding, algorithm, based, curvature, value, experiments, show, watermarking, robust, numerous, attacks, including, rst, transformations, smoothing, additive, random, noise, cropping, simplification, remeshing]"
1,4ab39729-af77-46f7-a662-16984fb9c1db,"[studied, autoassociative, neural, network, dynamic, synapses, include, facilitating, mechanism, developed, general, mean-field, framework, study, relevance, different, parameters, defining, dynamics, synapses, influence, collective, properties, network, depending, parameters, network, shows, different, types, behaviour, including, retrieval, phase, oscillatory, regime, non-retrieval, phase, oscillatory, phase, network, activity, continously, jumps, stored, patterns, compared, activity-dependent, mechanisms, synaptic, depression, synaptic, facilitation, enhances, network, ability, switch, among, stored, patterns, therefore, adaptation, external, stimuli, detailed, analysis, system, reflects, efficient-more, rapid, lesser, errors-network, access, stored, information, stronger, facilitation, also, present, set, monte, carlo, simulations, confirming, analytical, results]"
2,4ab3a4cf-1d96-4ce5-ab6f-b3e19fc260de,"[well-known, sturmian, sequences, non, ultimately, periodic, sequences, balanced, 2-letter, alphabet, also, characterized, complexity, exactly, n1, distinct, factors, length, n, natural, generalization, sturmian, sequences, set, infinite, episturmian, sequences, sequences, necessarily, balanced, k-letter, alphabet, necessarily, aperiodic, paper, characterize, balanced, episturmian, sequences, periodic, prove, fraenkels, conjecture, special, case, episturmian, sequences, appears, balanced, episturmian, sequences, ultimately, periodic, classified, 3, families]"
3,4ab3a98c-3620-47ec-b578-884ecf4a6206,"[one, fundamental, challenges, recognizing, actions, accounting, variability, arises, arbitrary, cameras, capture, humans, performing, actions, paper, explicitly, identify, three, important, sources, variability, 1, viewpoint, 2, execution, rate, 3, anthropometry, actors, propose, model, human, actions, allows, us, investigate, three, hypothesis, variability, associated, execution, action, closely, approximated, linear, combination, action, bases, joint, spatio-temporal, space, demonstrate, model, bounds, rank, matrix, image, measurements, bound, used, achieve, recognition, actions, based, imaged, data, test, employing, principal, angles, subspaces, robust, statistical, fluctuations, measurement, data, presented, find, membership, instance, action, algorithm, applied, recognize, several, actions, promising, results, obtained]"
4,4ab3b585-82b4-4207-91dd-b6bce7e27c4e,"[paper, generalizes, previous, optimal, upper, bounds, minimum, euclidean, distance, phase, shift, keying, psk, block, codes, explicit, three, parameters, alphabet, size, block, length]"

In [15]:
df.isnull().sum()

Unnamed: 0         0
abstract           0
authors            1
n_citation         0
references     40309
title              0
venue         103765
year               0
id                 0
dtype: int64

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 827533 entries, 0 to 827532
Data columns (total 9 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   Unnamed: 0  827533 non-null  int64
 1   abstract    827533 non-null  object
 2   authors     827532 non-null  object
 3   n_citation  827533 non-null  int64
 4   references  787224 non-null  object
 5   title       827533 non-null  object
 6   venue       723768 non-null  object
 7   year        827533 non-null  int64
 8   id          827533 non-null  object
dtypes: int64(3), object(6)
memory usage: 56.8+ MB

In [17]:
df = df.drop("Unnamed: 0", axis=1)

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 827533 entries, 0 to 827532
Data columns (total 8 columns):
 #   Column      Non-Null Count   Dtype
---  ------      --------------   -----
 0   abstract    827533 non-null  object
 1   authors     827532 non-null  object
 2   n_citation  827533 non-null  int64
 3   references  787224 non-null  object
 4   title       827533 non-null  object
 5   venue       723768 non-null  object
 6   year        827533 non-null  int64
 7   id          827533 non-null  object
dtypes: int64(2), object(6)
memory usage: 50.5+ MB

Realizando tokenização e removendo stopwords na coluna title

In [19]:
df[['id', 'title']].head()

,id,title
0,4ab3735c-80f1-472d-b953-fa0557fed28b,A new approach of 3D watermarking based on image segmentation
1,4ab39729-af77-46f7-a662-16984fb9c1db,Attractor neural networks with activity-dependent synapses: The role of synaptic facilitation
2,4ab3a4cf-1d96-4ce5-ab6f-b3e19fc260de,A characterization of balanced episturmian sequences
3,4ab3a98c-3620-47ec-b578-884ecf4a6206,Exploring the space of a human action
4,4ab3b585-82b4-4207-91dd-b6bce7e27c4e,Generalized upper bounds on the minimum distance of PSK block codes

In [20]:
#Removendo pontos, vírgulas e outros caracteres especiais mas mantendo o hífen de palavras compostas
df['title'] = df['title'].str.replace(r'[^\w\s-]', '', regex=True)

In [21]:
df['title'] = df['title'].apply(remove_stopwords)

In [22]:
df['title'] = df['title'].str.lower()

In [23]:
df['title'] = df['title'].str.split()

In [24]:
df[['id', 'title']].head()

,id,title
0,4ab3735c-80f1-472d-b953-fa0557fed28b,"[new, approach, 3d, watermarking, based, image, segmentation]"
1,4ab39729-af77-46f7-a662-16984fb9c1db,"[attractor, neural, networks, activity-dependent, synapses, role, synaptic, facilitation]"
2,4ab3a4cf-1d96-4ce5-ab6f-b3e19fc260de,"[characterization, balanced, episturmian, sequences]"
3,4ab3a98c-3620-47ec-b578-884ecf4a6206,"[exploring, space, human, action]"
4,4ab3b585-82b4-4207-91dd-b6bce7e27c4e,"[generalized, upper, bounds, minimum, distance, psk, block, codes]"

In [25]:
df[['id', 'title']].tail()

,id,title
827528,feb7d7ee-58d8-4a48-853e-c6751957997e,"[research, social, networking, sites, social, support, 2004, 2015, narrative, review, directions, future, research]"
827529,ff21f451-e914-4948-b1e4-0ef5971b365c,"[secured, mpr, node, selection, presence, cheating, nodes]"
827530,ff4623da-cc5a-4048-99ae-e5e906eb0a1b,"[digitally-controlled, h-bridge, dc-dc, converter, micropower, pv, energy, harvesting, system]"
827531,ff6217c8-a649-4db3-95ec-e1c55195ef4e,"[space-constrained, purification, dimethyl, ether, process, intensification, using, semicontinuous, dividing, wall, columns]"
827532,ff87696d-35fb-4872-aab5-5ff6285f10e6,"[characterization, uninorms, continuous, underlying, t-norm, t-conorm, means, ordinal, sum, construction]"

Realizando tokenização e removendo stopwords na coluna venue

In [26]:
df[['id', 'venue']].head()

,id,venue
0,4ab3735c-80f1-472d-b953-fa0557fed28b,international symposium on computers and communications
1,4ab39729-af77-46f7-a662-16984fb9c1db,Neurocomputing
2,4ab3a4cf-1d96-4ce5-ab6f-b3e19fc260de,Electronic Journal of Combinatorics
3,4ab3a98c-3620-47ec-b578-884ecf4a6206,international conference on computer vision
4,4ab3b585-82b4-4207-91dd-b6bce7e27c4e,Ima Journal of Mathematical Control and Information

In [27]:
#Removendo pontos, vírgulas e outros caracteres especiais mantendo o hífen de palavras compostas
df['venue'] = df['venue'].str.replace(r'[^\w\s-]', '', regex=True)

In [28]:
nao_textuais = df['venue'].apply(lambda x: not isinstance(x, str)).sum()

print(f"Existem {nao_textuais} valores não textuais na coluna 'venue'.")

Existem 103765 valores não textuais na coluna 'venue'.

In [29]:
df['venue'] = df['venue'].apply(remove_stopwords)

In [30]:
df['venue'] = df['venue'].str.lower()

In [31]:
df['venue'] = df['venue'].str.split()

In [32]:
df[['id', 'venue']].head()

,id,venue
0,4ab3735c-80f1-472d-b953-fa0557fed28b,"[international, symposium, computers, communications]"
1,4ab39729-af77-46f7-a662-16984fb9c1db,[neurocomputing]
2,4ab3a4cf-1d96-4ce5-ab6f-b3e19fc260de,"[electronic, journal, combinatorics]"
3,4ab3a98c-3620-47ec-b578-884ecf4a6206,"[international, conference, computer, vision]"
4,4ab3b585-82b4-4207-91dd-b6bce7e27c4e,"[ima, journal, mathematical, control, information]"

In [33]:
df[['id', 'venue']].tail()

,id,venue
827528,feb7d7ee-58d8-4a48-853e-c6751957997e,"[cyberpsychology, behavior, social, networking]"
827529,ff21f451-e914-4948-b1e4-0ef5971b365c,NaN
827530,ff4623da-cc5a-4048-99ae-e5e906eb0a1b,NaN
827531,ff6217c8-a649-4db3-95ec-e1c55195ef4e,"[computers, chemical, engineering]"
827532,ff87696d-35fb-4872-aab5-5ff6285f10e6,"[international, journal, approximate, reasoning]"

In [34]:
df.to_csv('resources/dblp-v10-tokenizado.csv', index=False)

In [ ]:
df.to_parquet('resources/dblp-v10-tokenizado.parquet')

: