In [25]:
import pandas as pd
import numpy as np

In [26]:
df = pd.read_csv('resources/dblp-v10.csv')

In [27]:
df.head()

,abstract,authors,n_citation,references,title,venue,year,id
0,"In this paper, a robust 3D triangular mesh wat...","['S. Ben Jabra', 'Ezzeddine Zagrouba']",50,"['09cb2d7d-47d1-4a85-bfe5-faa8221e644b', '10aa...",A new approach of 3D watermarking based on ima...,international symposium on computers and commu...,2008,4ab3735c-80f1-472d-b953-fa0557fed28b
1,We studied an autoassociative neural network w...,"['Joaquín J. Torres', 'Jesús M. Cortés', 'Joaq...",50,"['4017c9d2-9845-4ad2-ad5b-ba65523727c5', 'b118...",Attractor neural networks with activity-depend...,Neurocomputing,2007,4ab39729-af77-46f7-a662-16984fb9c1db
2,It is well-known that Sturmian sequences are t...,"['Genevi eve Paquin', 'Laurent Vuillon']",50,"['1c655ee2-067d-4bc4-b8cc-bc779e9a7f10', '2e4e...",A characterization of balanced episturmian seq...,Electronic Journal of Combinatorics,2007,4ab3a4cf-1d96-4ce5-ab6f-b3e19fc260de
3,One of the fundamental challenges of recognizi...,"['Yaser Sheikh', 'Mumtaz Sheikh', 'Mubarak Shah']",221,"['056116c1-9e7a-4f9b-a918-44eb199e67d6', '05ac...",Exploring the space of a human action,international conference on computer vision,2005,4ab3a98c-3620-47ec-b578-884ecf4a6206
4,This paper generalizes previous optimal upper ...,"['Efraim Laksman', 'Håkan Lennerstad', 'Magnus...",0,"['01a765b8-0cb3-495c-996f-29c36756b435', '5dbc...",Generalized upper bounds on the minimum distan...,Ima Journal of Mathematical Control and Inform...,2015,4ab3b585-82b4-4207-91dd-b6bce7e27c4e

In [28]:
df.tail()

,abstract,authors,n_citation,references,title,venue,year,id
999995,"In MANETs, exchange of data is carried out wit...","['Jeril Kuriakose', 'Sandeep Joshi']",0,NaN,Secured MPR node selection in the presence of ...,NaN,2016,ff21f451-e914-4948-b1e4-0ef5971b365c
999996,This paper presents a micro-power photovoltaic...,"['Anh Khoa Bui', 'ZheKai Xiao', 'Liter Siek']",0,"['079e437d-ac3a-473d-9ab5-1bbc0b1f0cf1', '318a...",Digitally-controlled H-bridge DC-DC converter ...,NaN,2016,ff4623da-cc5a-4048-99ae-e5e906eb0a1b
999997,"In this work, a distillation system is designe...","['Sarah E. Ballinger', 'Thomas A. Adams']",0,['ad799e60-dab7-49ec-96f4-b47b65c5a47f'],Space-constrained purification of dimethyl eth...,Computers & Chemical Engineering,2017,ff6217c8-a649-4db3-95ec-e1c55195ef4e
999998,NaN,"['Ben London', 'Bert Huang', 'Lise Getoor']",50,"['1c152bbb-3f77-4f83-a7d0-2a9b662f93b1', '218e...",Stability and Generalization in Structured Pre...,Journal of Machine Learning Research,2016,ff7553fa-88c0-431c-be85-8ec30024e420
999999,The uninorms with continuous underlying t-norm...,['Andrea Mesiarová-Zemánková'],50,"['27193256-3665-40d0-b04b-d78b63c590e9', '2c3a...",Characterization of uninorms with continuous u...,International Journal of Approximate Reasoning,2017,ff87696d-35fb-4872-aab5-5ff6285f10e6

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000000 entries, 0 to 999999
Data columns (total 8 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   abstract    827533 non-null   object
 1   authors     999998 non-null   object
 2   n_citation  1000000 non-null  int64
 3   references  875583 non-null   object
 4   title       1000000 non-null  object
 5   venue       822245 non-null   object
 6   year        1000000 non-null  int64
 7   id          1000000 non-null  object
dtypes: int64(2), object(6)
memory usage: 61.0+ MB

In [30]:
df.describe(include='all')

,abstract,authors,n_citation,references,title,venue,year,id
count,827533,999998,1000000.000000,875583,1000000,822245,1000000.000000,1000000
unique,825783,865803,NaN,807531,999064,4075,NaN,1000000
top,Quality and Reliability Engineering Internatio...,"['Irith Pomeranz', 'Sudhakar M. Reddy']",NaN,[],Letter from the Associate Editors.,"international conference on acoustics, speech,...",NaN,fd14f60b-9577-4461-824c-57611090cd02
freq,138,152,NaN,56395,4,11832,NaN,1
mean,NaN,NaN,36.000933,NaN,NaN,NaN,2009.447896,NaN
std,NaN,NaN,190.784498,NaN,NaN,NaN,7.032415,NaN
min,NaN,NaN,0.000000,NaN,NaN,NaN,1937.000000,NaN
25%,NaN,NaN,0.000000,NaN,NaN,NaN,2006.000000,NaN
50%,NaN,NaN,7.000000,NaN,NaN,NaN,2011.000000,NaN
75%,NaN,NaN,50.000000,NaN,NaN,NaN,2015.000000,NaN
max,NaN,NaN,42508.000000,NaN,NaN,NaN,2017.000000,NaN

In [31]:
df.isnull().sum()

abstract      172467
authors            2
n_citation         0
references    124417
title              0
venue         177755
year               0
id                 0
dtype: int64

In [32]:
quantidade_nulos = df['abstract'].isnull().sum()
porcentagem_nulos = (df['abstract'].isnull().mean()) * 100

print(f"Quantidade de nulos em 'abstract': {quantidade_nulos}")
print(f"Porcentagem de nulos em 'abstract': {porcentagem_nulos:.2f}%")

Quantidade de nulos em 'abstract': 172467
Porcentagem de nulos em 'abstract': 17.25%

Como o propósito do projeto é agrupar temas do RESUMO, então resumos nulos serão ignorados.

In [33]:
#dropar linhas onde o resumo é nulo
df_clean = df.dropna(subset=['abstract'])

df_clean.head()

,abstract,authors,n_citation,references,title,venue,year,id
0,"In this paper, a robust 3D triangular mesh wat...","['S. Ben Jabra', 'Ezzeddine Zagrouba']",50,"['09cb2d7d-47d1-4a85-bfe5-faa8221e644b', '10aa...",A new approach of 3D watermarking based on ima...,international symposium on computers and commu...,2008,4ab3735c-80f1-472d-b953-fa0557fed28b
1,We studied an autoassociative neural network w...,"['Joaquín J. Torres', 'Jesús M. Cortés', 'Joaq...",50,"['4017c9d2-9845-4ad2-ad5b-ba65523727c5', 'b118...",Attractor neural networks with activity-depend...,Neurocomputing,2007,4ab39729-af77-46f7-a662-16984fb9c1db
2,It is well-known that Sturmian sequences are t...,"['Genevi eve Paquin', 'Laurent Vuillon']",50,"['1c655ee2-067d-4bc4-b8cc-bc779e9a7f10', '2e4e...",A characterization of balanced episturmian seq...,Electronic Journal of Combinatorics,2007,4ab3a4cf-1d96-4ce5-ab6f-b3e19fc260de
3,One of the fundamental challenges of recognizi...,"['Yaser Sheikh', 'Mumtaz Sheikh', 'Mubarak Shah']",221,"['056116c1-9e7a-4f9b-a918-44eb199e67d6', '05ac...",Exploring the space of a human action,international conference on computer vision,2005,4ab3a98c-3620-47ec-b578-884ecf4a6206
4,This paper generalizes previous optimal upper ...,"['Efraim Laksman', 'Håkan Lennerstad', 'Magnus...",0,"['01a765b8-0cb3-495c-996f-29c36756b435', '5dbc...",Generalized upper bounds on the minimum distan...,Ima Journal of Mathematical Control and Inform...,2015,4ab3b585-82b4-4207-91dd-b6bce7e27c4e

In [34]:
quantidade_nulos = df_clean['abstract'].isnull().sum()
porcentagem_nulos = (df_clean['abstract'].isnull().mean()) * 100

print(f"Quantidade de nulos em 'abstract': {quantidade_nulos}")
print(f"Porcentagem de nulos em 'abstract': {porcentagem_nulos:.2f}%")

Quantidade de nulos em 'abstract': 0
Porcentagem de nulos em 'abstract': 0.00%

In [35]:
df_clean.isnull().sum()

abstract           0
authors            1
n_citation         0
references     40309
title              0
venue         103765
year               0
id                 0
dtype: int64

In [36]:
#salvar dataframe limpo em formato parquet para melhor desempenho
df_clean.to_parquet('resources/dblp-v10-clean.parquet')
df_clean.to_csv('resources/dblp-v10-clean.csv')